theme: minima

header_pages:
  - index.md
  - rlist.md
  - papers.md
  - problems.md

github_username: mcarmosi

author: maintained by Marco Carmosino

description: Exploring MCSP @ Simons

title: MCSP Working Group